### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by ashleydavis** [StratoDem/pandas.js#28]
Hi Michael, 

Just trying to get in touch with you. I noticed that you started this repository recently.

I've been working on something similar for the past year and I was wondering if you would be interested in joining me on the project?

https://github.com/data-forge/data-forge-js

Let me know if you are interested and we can Skype to talk about it.

You can contact me via ashley@codecapers.com.au

Cheers
Ash

**Comment by mjclawar** [comment]
Hi Ash,

Thanks for getting in touch and being interested in pandas.js! Love how data-forge looks and the functionality is great. 

At StratoDem, we're going to be using this repository for internal development and want the API to be as close to the Python pandas implementation as possible. We've open sourced this repository so others can use it as it develops into a more mature project. Since we've already had some structure planned in our backend around this implementation, we're going to continue to focus exclusively on this project for data manipulation, analysis and plotting in JavaScript.

**Comment by ashleydavis** [comment]
Ok that's cool, it helps evolve the JavaScript data analysis scene!

Feel free to get in touch and let me know how it's going. I'm signed for a book contract with Manning on JavaScript data analysis so I'm keen to understand what you are up to. I'm interested to hear from anyone who is improving the JavaScript ecosystem in that area.

**Comment by mjclawar** [comment]
Absolutely. It's always great to hear from someone else doing analysis in JS!
